// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `hello.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __hello_h__
#define __hello_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/ValueF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Comparable.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/GCObject.h>
#include <Ice/Value.h>
#include <Ice/Incoming.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/Optional.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace Test
{

class Hello;
class HelloPrx;

}

namespace Test
{

class Hello : public virtual ::Ice::Object
{
public:

    using ProxyType = HelloPrx;

    virtual bool ice_isA(::std::string, const ::Ice::Current&) const override;
    virtual ::std::vector<::std::string> ice_ids(const ::Ice::Current&) const override;
    virtual ::std::string ice_id(const ::Ice::Current&) const override;

    static const ::std::string& ice_staticId();

    virtual ::std::string SayHello(::std::string, const ::Ice::Current&) = 0;
    bool _iceD_SayHello(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&) override;
};

}

namespace Test
{

class HelloPrx : public virtual ::Ice::Proxy<HelloPrx, ::Ice::ObjectPrx>
{
public:

    ::std::string SayHello(const ::std::string& iceP_username, const ::Ice::Context& context = Ice::noExplicitContext)
    {
        return _makePromiseOutgoing<::std::string>(true, this, &Test::HelloPrx::_iceI_SayHello, iceP_username, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto SayHelloAsync(const ::std::string& iceP_username, const ::Ice::Context& context = Ice::noExplicitContext)
        -> decltype(::std::declval<P<::std::string>>().get_future())
    {
        return _makePromiseOutgoing<::std::string, P>(false, this, &Test::HelloPrx::_iceI_SayHello, iceP_username, context);
    }

    ::std::function<void()>
    SayHelloAsync(const ::std::string& iceP_username,
                  ::std::function<void(::std::string)> response,
                  ::std::function<void(::std::exception_ptr)> ex = nullptr,
                  ::std::function<void(bool)> sent = nullptr,
                  const ::Ice::Context& context = Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<::std::string>(response, ex, sent, this, &Test::HelloPrx::_iceI_SayHello, iceP_username, context);
    }

    void _iceI_SayHello(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::std::string>>&, const ::std::string&, const ::Ice::Context&);

    static const ::std::string& ice_staticId();

protected:

    HelloPrx() = default;
    friend ::std::shared_ptr<HelloPrx> IceInternal::createProxy<HelloPrx>();

    virtual ::std::shared_ptr<::Ice::ObjectPrx> _newInstance() const override;
};

}

namespace Ice
{

}

namespace Test
{

using HelloPtr = ::std::shared_ptr<Hello>;
using HelloPrxPtr = ::std::shared_ptr<HelloPrx>;

}

#else // C++98 mapping

namespace IceProxy
{

namespace Test
{

class Hello;
void _readProxy(::Ice::InputStream*, ::IceInternal::ProxyHandle< ::IceProxy::Test::Hello>&);
::IceProxy::Ice::Object* upCast(::IceProxy::Test::Hello*);

}

}

namespace Test
{

class Hello;
::Ice::Object* upCast(::Test::Hello*);
typedef ::IceInternal::Handle< ::Test::Hello> HelloPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::Test::Hello> HelloPrx;
typedef HelloPrx HelloPrxPtr;
void _icePatchObjectPtr(HelloPtr&, const ::Ice::ObjectPtr&);

}

namespace Test
{

class Callback_Hello_SayHello_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Hello_SayHello_Base> Callback_Hello_SayHelloPtr;

}

namespace IceProxy
{

namespace Test
{

class Hello : public virtual ::Ice::Proxy<Hello, ::IceProxy::Ice::Object>
{
public:

    ::std::string SayHello(const ::std::string& iceP_username, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return end_SayHello(_iceI_begin_SayHello(iceP_username, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_SayHello(const ::std::string& iceP_username, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_SayHello(iceP_username, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_SayHello(const ::std::string& iceP_username, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_SayHello(iceP_username, ::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_SayHello(const ::std::string& iceP_username, const ::Ice::Context& context, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_SayHello(iceP_username, context, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_SayHello(const ::std::string& iceP_username, const ::Test::Callback_Hello_SayHelloPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_SayHello(iceP_username, ::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_SayHello(const ::std::string& iceP_username, const ::Ice::Context& context, const ::Test::Callback_Hello_SayHelloPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_SayHello(iceP_username, context, del, cookie);
    }

    ::std::string end_SayHello(const ::Ice::AsyncResultPtr&);

private:

    ::Ice::AsyncResultPtr _iceI_begin_SayHello(const ::std::string&, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    static const ::std::string& ice_staticId();

protected:

    virtual ::IceProxy::Ice::Object* _newInstance() const;
};

}

}

namespace Test
{

class Hello : public virtual ::Ice::Object
{
public:

    typedef HelloPrx ProxyType;
    typedef HelloPtr PointerType;

    virtual ~Hello();

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::emptyCurrent) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::emptyCurrent) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::emptyCurrent) const;

    static const ::std::string& ice_staticId();

    virtual ::std::string SayHello(const ::std::string&, const ::Ice::Current& = ::Ice::emptyCurrent) = 0;
    bool _iceD_SayHello(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:

    virtual void _iceWriteImpl(::Ice::OutputStream*) const;
    virtual void _iceReadImpl(::Ice::InputStream*);
};

inline bool operator==(const Hello& lhs, const Hello& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) == static_cast<const ::Ice::Object&>(rhs);
}

inline bool operator<(const Hello& lhs, const Hello& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) < static_cast<const ::Ice::Object&>(rhs);
}

}

namespace Ice
{

}

namespace Test
{

template<class T>
class CallbackNC_Hello_SayHello : public Callback_Hello_SayHello_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::std::string&);

    CallbackNC_Hello_SayHello(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        ::Test::HelloPrx proxy = ::Test::HelloPrx::uncheckedCast(result->getProxy());
        ::std::string ret;
        try
        {
            ret = proxy->end_SayHello(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(ret);
        }
    }

private:

    Response _response;
};

template<class T> Callback_Hello_SayHelloPtr
newCallback_Hello_SayHello(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Hello_SayHello<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Hello_SayHelloPtr
newCallback_Hello_SayHello(T* instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Hello_SayHello<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_Hello_SayHello : public Callback_Hello_SayHello_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::std::string&, const CT&);

    Callback_Hello_SayHello(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        ::Test::HelloPrx proxy = ::Test::HelloPrx::uncheckedCast(result->getProxy());
        ::std::string ret;
        try
        {
            ret = proxy->end_SayHello(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(ret, CT::dynamicCast(result->getCookie()));
        }
    }

private:

    Response _response;
};

template<class T, typename CT> Callback_Hello_SayHelloPtr
newCallback_Hello_SayHello(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Hello_SayHello<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Hello_SayHelloPtr
newCallback_Hello_SayHello(T* instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Hello_SayHello<T, CT>(instance, cb, excb, sentcb);
}

}

#endif

#include <IceUtil/PopDisableWarnings.h>
#endif
